# docker-compose command
  # start -> docker-compose up
  # rebuild -> docker-compose up --build

  # tap 위치 맞추기

# version: docker-compose version
  # services: 실행하려는 컨테이너들 정의
    # redis-server: container name
      # container에서 사용하는 image
    # node-app: container name
      # build: current directory에 있는 Dockerfile 사용
      # ports: port mapping -> local : container

#-----------------------------------------------------------------

version: "3"
services:
  redis-server:
    image: "redis"
  node-app:
    build: .
    ports:
      - "5001:3000"
